Importa numpy

In [1]:
import numpy as np

crea un numpy array que tenga la siguente estructura

```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```

llamalo `array`

In [2]:
array = np.array([
    [1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
                )

averigua la forma del array

In [3]:
array.shape

(5, 3)

Selecciona la segunda columna del array

In [4]:
array

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [5]:
array[:,1]

array([ 6,  7,  8,  9, 10])

 Crea un vector con los valores del 15 al 55, llamalo array2
    
*pista: usa np.arange*

In [6]:
np.arange

In [7]:
array2 = np.arange(15,56)
array2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

asigna el valor 23 a la quinta posicion del array2

In [8]:
array2[4] = 23
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

convierte array2 del revés (es decir `[55,54,....,15]`

In [12]:
array2[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

Crea una matriz diagonal donde los elementos de la diagonal sean los 5 primeros valores pares de array2, llamala `matriz_diag`

*pista: usa np.diag*

In [14]:
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [19]:
np.diag(array2[1::2][:5])

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

In [35]:
matriz_diag = np.diag(array2[1::2][:5])
matriz_diag

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

Imprime el numero de dimensiones de `matriz_diag`

In [21]:
matriz_diag.ndim

2

Crea una matriz con números aleatorios de tamaño 5x3 (5 filas por 3 columnas), llamala `matriz`

In [31]:
np.random.random?

In [33]:
matriz = np.random.random((5,3))
matriz

array([[0.4800684 , 0.03671177, 0.70265864],
       [0.51836325, 0.71718869, 0.02066125],
       [0.39580117, 0.50445722, 0.11057736],
       [0.02868466, 0.44906291, 0.90281729],
       [0.36963183, 0.7334269 , 0.85622671]])

multiplica `matriz` por `matriz_diag`

In [24]:
matriz.shape

(5, 3)

In [25]:
matriz_diag.shape

(5, 5)

In [23]:
matriz @ matriz_diag

ValueError: shapes (5,3) and (5,5) not aligned: 3 (dim 1) != 5 (dim 0)

In [29]:
matriz.T.shape

(3, 5)

In [30]:
matriz.T @ matriz_diag

array([[ 7.10466847,  3.38937417,  8.71718885, 11.63148388, 15.7642687 ],
       [ 3.90492505,  6.31899942, 15.19713716,  5.25220565,  5.01831897],
       [ 0.3295339 ,  7.39985127,  7.61467526, 18.39196205, 15.37907544]])